[package]
name = "processor"
version = "0.1.0"
authors = ["esphas <esphas@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
simple_logger = "1.0.1"
libloading = "0.5.2"